os:
  - linux
  - osx
  - windows

language: minimal

env:
  - QTEST=${TRAVIS_BUILD_DIR}/qspec-1.3.3/test/test_mock.q

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source macos.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then source windows.sh; fi

script:
  - q $TRAVIS_BUILD_DIR/qspec-1.3.3/app/spec.q $QTEST
