os:
  - linux
  - osx

language: minimal

env:
  - QTEST=${TRAVIS_BUILD_DIR}/test_mock.q

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source macos.sh; fi

script:
  - q $QSPEC $QTEST
