language: minimal

install:
  - source linux.sh
  - conda install --yes -c kx kdb
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda activate base
  - bash -c "echo $KCLIC | base64 --decode > $QHOME/kc.lic"
  - conda install --yes -c jmcmurray qutil
  - wget https://github.com/nugend/qspec/archive/v1.3.3.zip
  - unzip v1.3.3.zip
  - ll $HOME/qspec-1.3.3/lib $QPATH/qspec

script:
  - q $HOME/qspec-1.3.3/app/spec.q $HOME/qspec-1.3.3/test/test/mock.q
